### ISSUE TITLE
Beam services operator does not restart failed flink jobs properly

### ISSUE THREAD

**Issue by oguzcankirmemis** [IndustryFusion/DigitalTwin#404]
After the core-services job fails due to some unknown reason, the CRD goes to 'UNKNOWN' state and the kopf operator is unable to  react on this. Furthermore, if the job is deleted in the unknown state, the operator gets stuck deleting a job that does not exist in flink anymore. The manual solution I have found is to delete the CRD, and the beam services operator, then rollback the CRD with helm.

**Comment by wagmarcel** [comment]
Official solution is to let Flink restart it. CRD is to deploy and update the job but cannot restart a job because Flink needs also to rebuild the state of the job.
Today, Flink is configured to try 10 restarts and then fail. We will move the the Exponential-restart mode where Flink tries indefinitely to restart the job but adds some backoff time when it fails.

**Comment by oguzcankirmemis** [comment]
Issue is recently solved, closing...
