### ISSUE TITLE
[EPIC] The ngsildUpdateBridge must be able to update and replace properties/relationship

### ISSUE THREAD

**Issue by wagmarcel** [IndustryFusion/DigitalTwin#556]
### Details
The NGSI-LD updateBridge API needs to be revised and documented to make sure we cover still what is needed
The RBAC use of the API needs to be reviewd
(what about subscription? merge?) Today we have Factory_Admin, Factory_Reader, Factory_Editor(?), Factory_Writer, Factory_Subscriber. We need an API Mapping to roles.

User Stories: #557

**Comment by MericFeyz** [comment]
Merge endpoints behave erroneously, an issue is [opened.](https://github.com/ScorpioBroker/ScorpioBroker/issues/578)

**Comment by MericFeyz** [comment]
Key findings about merge patch implementation:
- There are no unit tests for merge patch behavior neither for [singular](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/EntityManager/src/test/java/eu/neclab/ngsildbroker/entityhandler/controller/EntityControllerTest.java) entities nor [batch](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/EntityManager/src/test/java/eu/neclab/ngsildbroker/entityhandler/controller/EntityBatchControllerTest.java) handling, which makes the probability of a regression high.
- The main merge patch logic for singular entities is implemented as a postgresql [function](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/EntityManager/src/main/resources/db/migration/V20231015.2__mergepatch_preveandcurrentvalue.sql), which complicates debugging the issue. The most recent update to the function is from 15.10.2023, 10 months ago. For batch operations a separate but similar [function](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/EntityManager/src/main/resources/db/migration/V20240212.1__merge_batchops.sql) is defined, which is more recent.
- The surface level reading of the functions suggests an overwriting behavior resulting in a shallow merge instead of a recursive deep merge that is aligned with the specification.
- The implementation and the handled datatype makes using a dedicated Postgresql Debugger necessary to understand why exactly it fails.

**Comment by MericFeyz** [comment]
A [pull request](https://github.com/ScorpioBroker/ScorpioBroker/pull/597) was merged, which is supposed to fix the merge patch issue and some more (100k+ LOC change).

Also I received a response to the original issue claiming that the issue will be fixed with this upcoming change and a new release will be made soon including the implementation of NGSI-LD 1.8.1.

**Comment by MericFeyz** [comment]
A [new release](https://github.com/ScorpioBroker/ScorpioBroker/releases/tag/5.0.0-java-sqs) has been created. Aside from the merge fix, NGSI-LD 1.8.1 changes are implemented and there's a topics overhaul. Will check out how it fares

**Comment by yshashix** [comment]
Already tested Scorpio version 5.0.2 with merge request, 
 - deep merge possible
 - merge test to be implemented
Probably next week we can do rebase

**Comment by MericFeyz** [comment]
The datasetId in mergepatch issue:

https://github.com/ScorpioBroker/ScorpioBroker/issues/612

**Comment by MericFeyz** [comment]
> The datasetId in mergepatch issue:
> 
> https://github.com/ScorpioBroker/ScorpioBroker/issues/612

New release 5.0.3 claims to have fixed this, will rebase and see if it's working.
